### PR TITLE
added entity relationship diagram

### PR DESCRIPTION
**Pull request by collinsc**
1st draft of our relational database, it's pretty straightforward. I plan on going from here right to ORM, because the data model doesn't have anything fancy.

### CODE REVIEW

**Comment by BitFracture** [comment]
Nice. I am not familiar with the styling of the lines with perpendicular dashes and little tower-looking things, but looks good. What is the last_reply_ID attribute for Thread? If we are storing reply chains as a linked list, I would expect a similar attribute on Reply.

**Comment by collinsc** [comment]
@BitFracture `last_reply_id` was going back to a previous conversation where you wanted a way to remember the last comment. However now, in retrospect I would like to drop that attribute. 

I think we are much better off sorting on time. The reason I think this is because it's a little more maintainable, and if we needed to add the use case of `delete_thread` or `delete comment` it will be much easier to push that complexity into the dbms. I doubt we will need to store more than 100 reply entries so sorting will not be terrible. If we want thousands, then we need to move into a diffferent database design.

Notation on er diagram
image

**Comment by collinsc** [comment]
It's not a hard change to implement, and will save us writing code. Let me know if that sounds amenable, and I'll impement it.

Also postgres is really fast at sorting and counting.

**Comment by BitFracture** [comment]
I was suggesting before that we order the forum threads by their last update time. So we can either query the most recent reply and use that time to sort threads (slow, awful really) or we simply have an update_time attribute on a thread that is updated when a post is made in reference to it. 

If you want to simply sort on creation time for now, that is fine, but this is a pretty big usability thing with a forum.

**Comment by collinsc** [comment]
Oh got it thanks for reminding me. I forgot about that. I'll add it. However I think I am going to remove the count of replies variable. 

Postgresql count is supposed to be super efficient

**Comment by collinsc** [comment]
@BitFracture changes applied

**Review by BitFracture — APPROVED** [review]

**Pull request merged**
